#!/usr/bin/env bash

xhost local:
[ ! -d $HOME/irpf-2016-shared ] && mkdir $HOME/irpf-2016-shared
if [ "$(docker ps -a | grep irpf-2016 | wc -l)" == "1" ]; then
    docker start irpf-2016
else
    docker run -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix/:rw \
        -v /dev/snd:/dev/snd \
        -v $HOME/irpf-2016-shared:/root/shared:rw \
        --name irpf-2016 \
        irpf-2016 /bin/irpf-2016
fi
